### PR TITLE
[ON HOLD] Injecting the datalayer object onto the page.

### LINKED ISSUE #165: Add Datalayer
Data Layer inclusion on all pages e.g.
```
<script>
dataLayer = [{	
	'pageType'	: 'Home',
	'city'		: '',
	'state'		: '',	
	'region'	: '',
	'community'	: '',
	'model'		: '',
	'spec'		: ''
}];		
</script>
```

### PR DESCRIPTION
**Pull request by bhellema**
Fix #165 

Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/
- After: https://issue-165--hubblehomes-com--aemsites.hlx.page/

### CODE REVIEW

**Comment by samuelopra** [comment]
Just something to call out, for dataLayer in Nampa, seems that the pageType is "Search Results"
https://www.hubblehomes.com/new-homes/idaho/boise-metro/nampa
``
dataLayer = [{	
	'pageType'	: 'Search Results',
	'city'		: 'Nampa',
	'state'		: 'Idaho',	
	'region'	: 'Boise Metro',
	'community'	: '',
	'model'		: '',
	'spec'		: ''
}];		
```

where in this implementation it's home. First letters are also capitalized:
https://issue-165--hubblehomes-com--aemsites.hlx.page/new-homes/idaho/boise-metro/nampa

```
dataLayer = [{	
	'pageType'	: 'Search Results',
	'city'		: 'Nampa',
	'state'		: 'Idaho',	
	'region'	: 'Boise Metro',
	'community'	: '',
	'model'		: '',
	'spec'		: ''
}];
```

**Comment by bhellema** [comment]
> Search Results

I saw that too and it made no sense that the page was called Search Results as it provides no context.  I'm going to have to walk through the values they have with Nate and see what makes sense.  

Good catch on the case differences.  I intentionally toLowerCase everything for consistency as some of their results were all over the place.  Again, I'll chat with Nate to see what he would like to see.

**Review by kunwarsaluja — APPROVED** [review]
This looks good to me. Before we merge, we should run this through Nate to make sure if we are capturing all the data they need and data is flowing to the GTM site console.

**Comment by bhellema** [comment]
handled in https://github.com/aemsites/hubblehomes-com/pull/354

**Pull request closed without merging**
